# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake.exe

# The command to remove a file.
RM = /usr/local/bin/cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /cygdrive/e/study/mqtt/mqttClient/mqtt-c

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /cygdrive/e/study/mqtt/mqttClient/mqtt-c

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /cygdrive/e/study/mqtt/mqttClient/mqtt-c/CMakeFiles /cygdrive/e/study/mqtt/mqttClient/mqtt-c/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /cygdrive/e/study/mqtt/mqttClient/mqtt-c/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mqttc

# Build rule for target.
mqttc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mqttc
.PHONY : mqttc

# fast build rule for target.
mqttc/fast:
	$(MAKE) -f CMakeFiles/mqttc.dir/build.make CMakeFiles/mqttc.dir/build
.PHONY : mqttc/fast

#=============================================================================
# Target rules for targets named pub

# Build rule for target.
pub: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pub
.PHONY : pub

# fast build rule for target.
pub/fast:
	$(MAKE) -f CMakeFiles/pub.dir/build.make CMakeFiles/pub.dir/build
.PHONY : pub/fast

#=============================================================================
# Target rules for targets named sub

# Build rule for target.
sub: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sub
.PHONY : sub

# fast build rule for target.
sub/fast:
	$(MAKE) -f CMakeFiles/sub.dir/build.make CMakeFiles/sub.dir/build
.PHONY : sub/fast

lib/mqtt.o: lib/mqtt.c.o

.PHONY : lib/mqtt.o

# target to build an object file
lib/mqtt.c.o:
	$(MAKE) -f CMakeFiles/mqttc.dir/build.make CMakeFiles/mqttc.dir/lib/mqtt.c.o
.PHONY : lib/mqtt.c.o

lib/mqtt.i: lib/mqtt.c.i

.PHONY : lib/mqtt.i

# target to preprocess a source file
lib/mqtt.c.i:
	$(MAKE) -f CMakeFiles/mqttc.dir/build.make CMakeFiles/mqttc.dir/lib/mqtt.c.i
.PHONY : lib/mqtt.c.i

lib/mqtt.s: lib/mqtt.c.s

.PHONY : lib/mqtt.s

# target to generate assembly for a file
lib/mqtt.c.s:
	$(MAKE) -f CMakeFiles/mqttc.dir/build.make CMakeFiles/mqttc.dir/lib/mqtt.c.s
.PHONY : lib/mqtt.c.s

lib/mqtt_pal.o: lib/mqtt_pal.c.o

.PHONY : lib/mqtt_pal.o

# target to build an object file
lib/mqtt_pal.c.o:
	$(MAKE) -f CMakeFiles/mqttc.dir/build.make CMakeFiles/mqttc.dir/lib/mqtt_pal.c.o
.PHONY : lib/mqtt_pal.c.o

lib/mqtt_pal.i: lib/mqtt_pal.c.i

.PHONY : lib/mqtt_pal.i

# target to preprocess a source file
lib/mqtt_pal.c.i:
	$(MAKE) -f CMakeFiles/mqttc.dir/build.make CMakeFiles/mqttc.dir/lib/mqtt_pal.c.i
.PHONY : lib/mqtt_pal.c.i

lib/mqtt_pal.s: lib/mqtt_pal.c.s

.PHONY : lib/mqtt_pal.s

# target to generate assembly for a file
lib/mqtt_pal.c.s:
	$(MAKE) -f CMakeFiles/mqttc.dir/build.make CMakeFiles/mqttc.dir/lib/mqtt_pal.c.s
.PHONY : lib/mqtt_pal.c.s

sample/pub.o: sample/pub.c.o

.PHONY : sample/pub.o

# target to build an object file
sample/pub.c.o:
	$(MAKE) -f CMakeFiles/pub.dir/build.make CMakeFiles/pub.dir/sample/pub.c.o
.PHONY : sample/pub.c.o

sample/pub.i: sample/pub.c.i

.PHONY : sample/pub.i

# target to preprocess a source file
sample/pub.c.i:
	$(MAKE) -f CMakeFiles/pub.dir/build.make CMakeFiles/pub.dir/sample/pub.c.i
.PHONY : sample/pub.c.i

sample/pub.s: sample/pub.c.s

.PHONY : sample/pub.s

# target to generate assembly for a file
sample/pub.c.s:
	$(MAKE) -f CMakeFiles/pub.dir/build.make CMakeFiles/pub.dir/sample/pub.c.s
.PHONY : sample/pub.c.s

sample/sub.o: sample/sub.c.o

.PHONY : sample/sub.o

# target to build an object file
sample/sub.c.o:
	$(MAKE) -f CMakeFiles/sub.dir/build.make CMakeFiles/sub.dir/sample/sub.c.o
.PHONY : sample/sub.c.o

sample/sub.i: sample/sub.c.i

.PHONY : sample/sub.i

# target to preprocess a source file
sample/sub.c.i:
	$(MAKE) -f CMakeFiles/sub.dir/build.make CMakeFiles/sub.dir/sample/sub.c.i
.PHONY : sample/sub.c.i

sample/sub.s: sample/sub.c.s

.PHONY : sample/sub.s

# target to generate assembly for a file
sample/sub.c.s:
	$(MAKE) -f CMakeFiles/sub.dir/build.make CMakeFiles/sub.dir/sample/sub.c.s
.PHONY : sample/sub.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... mqttc"
	@echo "... pub"
	@echo "... sub"
	@echo "... edit_cache"
	@echo "... lib/mqtt.o"
	@echo "... lib/mqtt.i"
	@echo "... lib/mqtt.s"
	@echo "... lib/mqtt_pal.o"
	@echo "... lib/mqtt_pal.i"
	@echo "... lib/mqtt_pal.s"
	@echo "... sample/pub.o"
	@echo "... sample/pub.i"
	@echo "... sample/pub.s"
	@echo "... sample/sub.o"
	@echo "... sample/sub.i"
	@echo "... sample/sub.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

